# Generated by Django 4.1 on 2022-08-11 12:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_type_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='occupants',
            field=models.ManyToManyField(blank=True, related_name='occupant', to=settings.AUTH_USER_MODEL),
        ),
    ]
